# -*- coding: utf-8 -*-
"""nocoesOO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/clovesrocha/MiniCursoIP/blob/master/nocoesOO.ipynb
"""

# DOCENTE: Prof. MSc. Cloves
# AULA X: Python Noções OO
# Estudante: ...

class Automovel:
    def __init__(self, placa='xx-123'):
        self.placa = placa

    def get_placa(self):
        return self.placa

    def dirigir(self, velocidade):
        print(f'Estou dirigindo a {velocidade} km/h')

# Exemplo de uso da classe Automovel
carro = Automovel()
print(carro.get_placa())
carro.dirigir(60)

class Pessoa:
    def __init__(self, nome, idade, endereco, sexo):
        self.nome = nome
        self.idade = idade
        self.endereco = endereco
        self.sexo = sexo

    def apresentar(self):
        return f"Olá, meu nome é {self.nome}, tenho {self.idade} anos, moro em {self.endereco} e sou do sexo {self.sexo}."

# Criando uma instância da classe Pessoa
pessoa1 = Pessoa('Cloves', 38, 'Rua Principal, 123', 'Masculino')

# Acessando os atributos e método da instância
print(pessoa1.nome)  # Saída: Cloves
print(pessoa1.idade)  # Saída: 38
print(pessoa1.apresentar())  # Saída: Olá, meu nome é Cloves, tenho 38 anos, moro em Rua Principal, 123 e sou do sexo Masculino.

class Pessoa:
    def __init__(self, nome, idade, endereco, genero):
        self.nome = nome
        self.idade = idade
        self.endereco = endereco
        self.genero = genero

    def apresentar(self):
        return f"Nome: {self.nome}, Idade: {self.idade}, Endereço: {self.endereco}, Gênero: {self.genero}"

class Cadastro:
    def __init__(self):
        self.pessoas = []

    def adicionar_pessoa(self, pessoa):
        self.pessoas.append(pessoa)

    def listar_pessoas(self):
        for pessoa in self.pessoas:
            print(pessoa.apresentar())

# Criando uma instância da classe Cadastro
cadastro = Cadastro()

# Criando instâncias da classe Pessoa e adicionando ao cadastro
pessoa1 = Pessoa("Cloves", 38, "Rua Principal, 123", "Masculino")
pessoa2 = Pessoa("Maria", 25, "Avenida Secundária, 456", "Feminino")

cadastro.adicionar_pessoa(pessoa1)
cadastro.adicionar_pessoa(pessoa2)

# Listando as pessoas no cadastro
cadastro.listar_pessoas()